### PR TITLE
CMake: Adding target "xtensor-blas" which readily links lapack and blas

### LINKED ISSUE #143: Include lapack and blas libraries in CMake targets
It would be great to allow the end-user to only have to 

```cmake
target_link_libraries(... xsimd) 
```

(without having to deal with blas and lapack)

See https://github.com/xtensor-stack/xsimd/issues/332

### PR DESCRIPTION
**Pull request by tdegeus**
Adding target "xtensor-blas" which readily links lapack and blas. This way one only has to 

```cmake
find_package(xtensor-blas)
target_link_libraries(myproject xtensor-blas)
```

Fixes #143

### CODE REVIEW

**Comment by tdegeus** [comment]
Can anyone have a look at the CI, is seems to fails for reasons unrelated to this PR?

**Comment by JohanMabille** [comment]
That's the same issue with travis as the ont I'm experiencing with xtensor.

**Comment by tdegeus** [comment]
I will extend this with the C++ version

**Comment by tdegeus** [comment]
Any chance that we could integrate this in the conda version soon 😬? @wolfv @JohanMabille

**Comment by JohanMabille** [comment]
Yes I am going to release xtensor soon (this weekend or the beginning of next week) and then upgrade and release the stack.

**Comment by tdegeus** [comment]
@JohanMabille Great! Then I'll be quick to open PRs with the c++ version in the target

**Pull request merged**
